```yaml
name: Daily Quote Sender

on:
  schedule:
    - cron: '30 1 * * *'  # 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:  # Allows manual testing

jobs:
  send-quote:
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Daily Quote
      run: |
        # Get a random quote
        QUOTE_DATA=$(curl -s "https://api.quotable.io/random")
        QUOTE_TEXT=$(echo $QUOTE_DATA | jq -r '.content')
        QUOTE_AUTHOR=$(echo $QUOTE_DATA | jq -r '.author')
        
        # Create the message with light theme styling
        MESSAGE="🌅 *Good Morning!*

🌸 _Your Daily Inspiration_ 🌸

💭 \"$QUOTE_TEXT\"

✨ *— $QUOTE_AUTHOR*

🌻 Have a beautiful day ahead! 🌻"
        
        # Send to Telegram
        curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${{ secrets.CHAT_ID }}\",
            \"text\": \"$MESSAGE\",
            \"parse_mode\": \"Markdown\"
          }"
        
        echo "Quote sent successfully!"
```
